spring.application.name=spring-mongo
spring.mongodb.uri=mongodb+srv://kauanfiolo_db_user:fpw5yiLJcxzI1BHl@cluster.ztf0ki0.mongodb.net/spring_boot_mongo?readPreference=nearest&authSource=admin&authMechanism=SCRAM-SHA-1
logging.level.org.mongodb.driver=DEBUG
